CREATE TABLE CODIGOANP (
    CODIGO VARCHAR(10),
    DESCRICAO VARCHAR(1000));

INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('810201001', 'ÁLCOOL METÍLICO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101001', 'BIODIESEL B100');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101010', 'BIODIESEL FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610101009', 'BRIGHT STOCK');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210202003', 'BUTADIENO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210202001', 'BUTANO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210202002', 'BUTANO ESPECIAL');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620501002', 'CICLO DIESEL');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620501001', 'CICLO OTTO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610101005', 'CILINDRO I');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610101006', 'CILINDRO II');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620601003', 'CORRENTE DE MOTOSSERRA');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('340101002', 'DERIVADOS LEVES INTERMEDIÁRIOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('560101002', 'DERIVADOS PESADOS INTERMEDIÁRIOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101026', 'DIESEL B S1800 PARA GERAÇÃO DE ENERGIA ELÉTRICA');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101032', 'DIESEL B S50 PARA GERAÇÃO DE ENERGIA ELÉTRICA');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101027', 'DIESEL B S500 PARA GERAÇÃO DE ENERGIA ELÉTRICA');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101004', 'DIESEL B10');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101005', 'DIESEL B15');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101022', 'DIESEL B2 ESPECIAL - 200 PPM ENXOFRE');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101014', 'DIESEL B20 S1800 - ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101006', 'DIESEL B20 S1800 - COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101031', 'DIESEL B20 S50 ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101030', 'DIESEL B20 S50 COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101016', 'DIESEL B20 S500 - ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101015', 'DIESEL B20 S500 - COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101025', 'DIESEL B30');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101007', 'DIESEL B4 S1800 - ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101002', 'DIESEL B4 S1800 - COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101009', 'DIESEL B4 S500 - ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101008', 'DIESEL B4 S500 - COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101017', 'DIESEL MARÍTIMO - DMA B2');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101018', 'DIESEL MARÍTIMO - DMA B5');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101019', 'DIESEL MARÍTIMO - DMB B2');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101020', 'DIESEL MARÍTIMO - DMB B5');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101021', 'DIESEL NÁUTICO B2 ESPECIAL - 200 PPM ENXOFRE');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420201001', 'DMA - MGO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420201003', 'DMB - MDO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620101002', 'ENGRENAGENS E SISTEMAS CIRCULATÓRIOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620101007', 'ESTAMPAGEM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210301001', 'ETANO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('810102001', 'ETANOL ANIDRO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('810102004', 'ETANOL ANIDRO COM CORANTE');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('810102002', 'ETANOL ANIDRO FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('810102003', 'ETANOL ANIDRO PADRÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('810101002', 'ETANOL HIDRATADO ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('810101001', 'ETANOL HIDRATADO COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('810101003', 'ETANOL HIDRATADO FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210301002', 'ETENO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210302004', 'GÁS ÁCIDO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210101001', 'GÁS COMBUSTÍVEL');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210302003', 'GÁS DE XISTO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210302002', 'GÁS INTERMEDIÁRIO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210204001', 'GÁS LIQUEFEITO INTERMEDIÁRIO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('220101003', 'GÁS NATURAL COMPRIMIDO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('220101004', 'GÁS NATURAL LIQUEFEITO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('220101002', 'GÁS NATURAL SECO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('220101001', 'GÁS NATURAL ÚMIDO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('220101005', 'GÁS NATURAL VEICULAR');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('220101006', 'GÁS NATURAL VEICULAR PADRÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('520101001', 'GASÓLEOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320101001', 'GASOLINA A COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320101003', 'GASOLINA A FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320101002', 'GASOLINA A PREMIUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320103001', 'GASOLINA AUTOMOTIVA PADRÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320102002', 'GASOLINA C ADITIVADA');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320102001', 'GASOLINA C COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320102004', 'GASOLINA C FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320102003', 'GASOLINA C PREMIUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320201001', 'GASOLINA DE AVIAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320201002', 'GASOLINA DE AVIAÇÃO FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('220102001', 'GASOLINA NATURAL (C5+)');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320301002', 'GASOLINA PARA EXPORTAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210203001', 'GLP');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210203002', 'GLP FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('650101001', 'GRAXAS MINERAIS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620101001', 'HIDRÁULICO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610201001', 'HIDROGENADO LEVE');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610201002', 'HIDROGENADO MÉDIO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610201003', 'HIDROGENADO PESADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620101004', 'ISOLANTE TIPO A');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620101005', 'ISOLANTE TIPO B');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('220102002', 'LÍQUIDO DE GÁS NATURAL');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('640201001', 'MACROOLEOSAS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('640101001', 'MICROOLEOSAS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620502001', 'MOTORES 2 TEMPOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610101002', 'NEUTRO LEVE');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610401002', 'NEUTRO LEVE RR');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610101003', 'NEUTRO MÉDIO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610401003', 'NEUTRO MÉDIO RR');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610101004', 'NEUTRO PESADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610401004', 'NEUTRO PESADO RR');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510101003', 'ÓLEO COMBUSTÍVEL A FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510101001', 'ÓLEO COMBUSTÍVEL A1');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510101002', 'ÓLEO COMBUSTÍVEL A2');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510102003', 'ÓLEO COMBUSTÍVEL B FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510102001', 'ÓLEO COMBUSTÍVEL B1');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510102002', 'ÓLEO COMBUSTÍVEL B2');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510201001', 'ÓLEO COMBUSTÍVEL MARÍTIMO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510201002', 'ÓLEO COMBUSTÍVEL MARÍTIMO FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510201003', 'ÓLEO COMBUSTÍVEL MARÍTIMO MISTURA (MF)');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510301003', 'ÓLEO COMBUSTÍVEL PARA GERAÇÃO ELÉTRICA');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('560101001', 'ÓLEO DE XISTO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420105001', 'ÓLEO DIESEL A S10');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420101005', 'ÓLEO DIESEL A S1800 - ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420101004', 'ÓLEO DIESEL A S1800 - COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420101003', 'ÓLEO DIESEL A S1800 - FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420102006', 'ÓLEO DIESEL A S50');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420102005', 'ÓLEO DIESEL A S500 - ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420102004', 'ÓLEO DIESEL A S500 - COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420102003', 'ÓLEO DIESEL A S500 - FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420104001', 'ÓLEO DIESEL AUTOMOTIVO ESPECIAL - ENXOFRE 200 PPM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101033', 'ÓLEO DIESEL B S10 - ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101034', 'ÓLEO DIESEL B S10 - COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101011', 'ÓLEO DIESEL B S1800 - ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101003', 'ÓLEO DIESEL B S1800 - COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101028', 'ÓLEO DIESEL B S50 - ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101029', 'ÓLEO DIESEL B S50 - COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101013', 'ÓLEO DIESEL B S500 - ADITIVADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('820101012', 'ÓLEO DIESEL B S500 - COMUM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420301003', 'ÓLEO DIESEL FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420201002', 'ÓLEO DIESEL MARÍTIMO FORA DE ESPECIFICAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420202001', 'ÓLEO DIESEL NÁUTICO ESPECIAL - ENXOFRE 200 PPM');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420301001', 'ÓLEO DIESEL PADRÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610601001', 'ÓLEOS BÁSICOS - GRUPO II');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610701001', 'ÓLEOS BÁSICOS - GRUPO III');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510301002', 'ÓLEOS COMBUSTÍVEIS PARA EXPORTAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620601001', 'ÓLEOS EXTENSORES E PLASTIFICANTES');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('660101001', 'ÓLEOS LUB. PARAF E GRAXAS INTERMEDIÁRIOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620401001', 'ÓLEOS LUBRIFICANTES FERROVIÁRIOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620301001', 'ÓLEOS LUBRIFICANTES MARÍTIMOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620201001', 'ÓLEOS LUBRIFICANTES PARA AVIAÇÃO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('630101001', 'ÓLEOS LUBRIFICANTES USADOS OU CONTAMINADOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320301001', 'OUTRAS GASOLINAS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('320103002', 'OUTRAS GASOLINAS AUTOMOTIVAS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('650101002', 'OUTRAS GRAXAS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('640401001', 'OUTRAS PARAFINAS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('810201002', 'OUTROS ALCOÓIS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('340101003', 'OUTROS DERIVADOS LEVES');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('560101003', 'OUTROS DERIVADOS PESADOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210302001', 'OUTROS GASES');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210204002', 'OUTROS GASES LIQUEFEITOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610201004', 'OUTROS NAFTÊNICOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('510301001', 'OUTROS ÓLEOS COMBUSTÍVEIS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('420301002', 'OUTROS ÓLEOS DIESEL');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620601004', 'OUTROS ÓLEOS LUBRIFICANTES ACABADOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620505001', 'OUTROS ÓLEOS LUBRIFICANTES AUTOMOTIVOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610501001', 'OUTROS ÓLEOS LUBRIFICANTES BÁSICOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620101008', 'OUTROS ÓLEOS LUBRIFICANTES INDUSTRIAIS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610101010', 'OUTROS PARAFÍNICOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610302001', 'OUTROS SINTÉTICOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610301001', 'POLIALFAOLEFINA');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620101003', 'PROCESSO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210201001', 'PROPANO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210201002', 'PROPANO ESPECIAL');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('210201003', 'PROPENO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620601002', 'PULVERIZAÇÃO AGRÍCOLA');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('550101001', 'RESÍDUO AROMÁTICO (RARO)');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('550101005', 'RESÍDUO ASFÁLTICO(RASF)');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('550101002', 'RESÍDUO ATMOSFÉRICO (RAT)');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('550101003', 'RESÍDUO DE VÁCUO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('550101004', 'RESÍDUO DE VÁCUO DE ALTO TEOR DE ENXOGRE');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610101001', 'SPINDLE');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610401001', 'SPINDLE RR');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620101006', 'TÊXTIL / AMACIANTE DE FIBRAS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620504001', 'TRANSMISSÃO AUTOMÁTICA');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('620503001', 'TRANSMISSÕES E SISTEMAS HIDRÁULICOS');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610101007', 'TURBINA LEVE');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('610101008', 'TURBINA PESADO');
INSERT INTO CODIGOANP (CODIGO, DESCRICAO)
               VALUES ('640301001', 'VASELINA');

COMMIT WORK;
