CREATE TABLE CFOPCONVERSAO (
    CFOPCOMPRA VARCHAR(10),
    CFOPENTRADA VARCHAR(10)
	);

INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5101', '1102');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5102', '1102');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5104', '1102');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5106', '1102');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5401', '1403');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5402', '1403');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5403', '1403');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5405', '1403');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5109', '1122');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5152', '1152');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5202', '1202');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5409', '1409');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5411', '1411');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5910', '1910');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5929', '1949');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6101', '2102');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6102', '2102');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6104', '2102');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('5106', '2102');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6401', '2403');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6402', '2403');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6403', '2403');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6404', '2403');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6409', '2409');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6152', '2152');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6202', '2202');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6409', '2409');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6411', '2411');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6410', '2910');
INSERT INTO CFOPCONVERSAO (CFOPCOMPRA, CFOPENTRADA)
                   VALUES ('6929', '2949');

COMMIT WORK;