/******************************************************************************/
/***               Generated 27/10/2021 23:20:32                            ***/
/******************************************************************************/
SET SQL DIALECT 3;
/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/
CREATE GENERATOR GEN_CFOP_ID;

CREATE TABLE CFOP (
    ID         INTEGER NOT NULL,
    CFOP       INTEGER,
    TIPO       VARCHAR(1),
    DESCRICAO  VARCHAR(500)
);
/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/
ALTER TABLE CFOP ADD CONSTRAINT PK_CFOP PRIMARY KEY (ID);
/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/
CREATE INDEX CFOP_IDX1 ON CFOP (CFOP);
CREATE INDEX CFOP_IDX2 ON CFOP (DESCRICAO);
CREATE INDEX CFOP_IDX3 ON CFOP (TIPO);
/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/
SET TERM ^ ;
/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/
/* Trigger: CFOP_BI */
CREATE OR ALTER TRIGGER CFOP_BI FOR CFOP
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_cfop_id,1);
end
^
SET TERM ; ^

/******************************************************************************/
/***                               Privileges                               ***/
/******************************************************************************/
ALTER SEQUENCE GEN_CFOP_ID RESTART WITH 0;
DELETE FROM cfop;
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2000', 'ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DE OUTROS ESTADOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3000', 'ENTRADAS OU AQUISIÇÕES DE SERVIÇOS DO EXTERIOR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1102', 'COMPRA PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1152', 'TRANSFERÊNCIA PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1124', 'INDUSTRIALIZAÇÃO EFETUADA POR OUTRA EMPRESA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1125', 'INDUSTRIALIZAÇÃO EFETUADA POR OUTRA EMPRESA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1101', 'COMPRA PARA INDUSTRIALIZAÇÃO OU PRODUÇÃO RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1153', 'TRANSFERÊNCIA DE ENERGIA ELÉTRICA PARA DISTRIBUIÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1154', 'TRANSFERÊNCIA PARA UTILIZAÇÃO NA PRESTAÇÃO DE SERVIÇO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1151', 'TRANSFERÊNCIA PARA INDUSTRIALIZAÇÃO OU PRODUÇÃO RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1126', 'COMPRA PARA UTILIZAÇÃO NA PRESTAÇÃO DE SERVIÇO SUJEITA AO ICMS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1128', 'COMPRA PARA UTILIZAÇÃO NA PRESTAÇÃO DE SERVIÇO SUJEITA AO ISSQN');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1118', 'COMPRA DE MERC. PARA COMERCIALIZAÇÃO PELO ADQUIRENTE ORIGINÁRIO.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1117', 'COMPRA PARA COMERCIALIZAÇÃO ORIGINADA DE ENCOMENDA PARA RECEBIMENTO FUTURO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1122', 'COMPRA PARA INDUSTRIALIZAÇÃO, EM VENDA À ORDEM, JÁ RECEBIDA DO VENDEDOR REMETENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1113', 'COMPRA PARA COMERCIALIZAÇÃO, DE MERCADORIA RECEBIDA ANTERIORMENTE EM CONSIGNAÇÃO MERCANTIL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1111', 'COMPRA PARA INDUSTRIALIZAÇÃO DE MERCADORIA RECEBIDA ANTERIORMENTE EM CONSIGNAÇÃO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1116', 'COMPRA PARA INDUSTRIALIZAÇÃO OU PRODUÇÃO RURAL ORIGINADA DE ENCOMENDA PARA RECEBIMENTO FUTURO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1150', 'TRANSFERÊNCIAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2102', 'COMPRA PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2152', 'TRANSFERÊNCIA PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2124', 'INDUSTRIALIZAÇÃO EFETUADA POR OUTRA EMPRESA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2101', 'COMPRA PARA INDUSTRIALIZAÇÃO OU PRODUÇÃO RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2153', 'TRANSFERÊNCIA DE ENERGIA ELÉTRICA PARA DISTRIBUIÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2151', 'TRANSFERÊNCIA PARA INDUSTRIALIZAÇÃO OU PRODUÇÃO RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2154', 'TRANSFERÊNCIA PARA UTILIZAÇÃO NA PRESTAÇÃO DE SERVIÇO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2126', 'COMPRA PARA UTILIZAÇÃO NA PRESTAÇÃO DE SERVIÇO SUJEITA AO ICMS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2128', 'COMPRA PARA UTILIZAÇÃO NA PRESTAÇÃO DE SERVIÇO SUJEITA AO ISSQN');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2117', 'COMPRA PARA COMERCIALIZAÇÃO ORIGINADA DE ENCOMENDA PARA RECEBIMENTO FUTURO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2120', 'COMPRA PARA COMERCIALIZAÇÃO, EM VENDA À ORDEM, JÁ RECEBIDA DO VENDEDOR REMETENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2120', 'COMPRA PARA INDUSTRIALIZAÇÃO, EM VENDA À ORDEM, JÁ RECEBIDA DO VENDEDOR REMETENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2100', 'COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2125', 'INDUST. EFETUADA POR OUTRA EMPRESA QUANDO A MERC. REMETIDA PARA UTILIZAÇÃO NO PROCESSO.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2118', 'COMPRA DE MERC PARA COMERC. PELO ADQUIRENTE ORIGINÁRIO ENTREGUE PELO VENDEDOR REMETENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2113', 'COMPRA PARA COMERCIALIZAÇÃO, DE MERCADORIA RECEBIDA ANTERIORMENTE EM CONSIGNAÇÃO MERCANTIL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2111', 'COMPRA PARA INDUSTRIALIZAÇÃO DE MERCADORIA RECEBIDA ANTERIORMENTE EM CONSIGNAÇÃO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2116', 'COMPRA PARA INDUSTRIALIZAÇÃO OU PRODUÇÃO RURAL ORIGINADA DE ENCOMENDA PARA RECEBIMENTO FUTURO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2150', 'TRANSFERÊNCIAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2122', 'COMPRA PARA INDUSTRIALIZAÇÃO EM QUE A MERCADORIA FOI REMETIDA PELO FORNECEDOR AO INDUSTRIALIZADOR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3102', 'COMPRA PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3127', 'COMPRA PARA INDUSTRIALIZAÇÃO SOB O REGIME DE DRAWBACK');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3126', 'COMPRA PARA UTILIZAÇÃO NA PRESTAÇÃO DE SERVIÇO SUJEITA AO ICMS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3128', 'COMPRA PARA UTILIZAÇÃO NA PRESTAÇÃO DE SERVIÇO SUJEITA AO ISSQN');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3100', 'COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU PRESTAÇÃO DE SERVIÇOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1250', 'COMPRAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1253', 'COMPRA DE ENERGIA ELÉTRICA POR ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1252', 'COMPRA DE ENERGIA ELÉTRICA POR ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1257', 'COMPRA DE ENERGIA ELÉTRICA PARA CONSUMO POR DEMANDA CONTRATADA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1251', 'COMPRA DE ENERGIA ELÉTRICA PARA DISTRIBUIÇÃO OU COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1206', 'ANULAÇÃO DE VALOR RELATIVO À PRESTAÇÃO DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1205', 'ANULAÇÃO DE VALOR RELATIVO À PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1256', 'COMPRA DE ENERGIA ELÉTRICA POR ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1202', 'DEVOLUÇÃO DE VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1208', 'DEVOLUÇÃO DE PRODUÇÃO DO ESTABELECIMENTO, REMETIDA EM TRANSFERÊNCIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1254', 'COMPRA DE ENERGIA ELÉTRICA POR ESTABELECIMENTO PRESTADOR DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1255', 'COMPRA DE ENERGIA ELÉTRICA POR ESTABELECIMENTO PRESTADOR DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1209', 'DEVOL. DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, REMETIDA EM TRANSFERÊNCIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1204', 'DEVOL. DE VENDA DE MERCAD. ADQUI. OU RECEB. DE TERCEIROS, DESTINADA À ZONA FRANCA DE MANAUS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1200', 'DEVOL. DE VENDAS DE PRODUÇÃO DO ESTABELEC., DE PRODUTOS DE TERCEIROS OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1203', 'DEVOL. DE VENDA DE PRODUÇÃO DO ESTABELEC. DESTIN. À ZONA FRANCA DE MANAUS OU ÁREAS DE LIVRE COMERCIO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2250', 'COMPRAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2201', 'DEVOLUÇÃO DE VENDA DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2203', 'DEVOLUÇÃO DE VENDA DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2207', 'ANULAÇÃO DE VALOR RELATIVO À VENDA DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2253', 'COMPRA DE ENERGIA ELÉTRICA POR ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2252', 'COMPRA DE ENERGIA ELÉTRICA POR ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2257', 'COMPRA DE ENERGIA ELÉTRICA PARA CONSUMO POR DEMANDA CONTRATADA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2251', 'COMPRA DE ENERGIA ELÉTRICA PARA DISTRIBUIÇÃO OU COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2206', 'ANULAÇÃO DE VALOR RELATIVO À PRESTAÇÃO DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2205', 'ANULAÇÃO DE VALOR RELATIVO À PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2256', 'COMPRA DE ENERGIA ELÉTRICA POR ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2202', 'DEVOLUÇÃO DE VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2204', 'DEVOLUÇÃO DE VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2208', 'DEVOLUÇÃO DE PRODUÇÃO DO ESTABELECIMENTO, REMETIDA EM TRANSFERÊNCIA.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2251', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE PARA EXECUÇÃO DE SERVIÇO DA MESMA NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2254', 'COMPRA DE ENERGIA ELÉTRICA POR ESTABELECIMENTO PRESTADOR DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2255', 'COMPRA DE ENERGIA ELÉTRICA POR ESTABELECIMENTO PRESTADOR DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2209', 'DEVOLUÇÃO DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS E REMETIDA EM TRANSFERÊNCIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2200', 'DEVOLUÇÕES DE VENDAS DE PRODUÇÃO DO ESTABELECIMENTO OU DE TERCEIROS OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3250', 'COMPRAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3201', 'DEVOLUÇÃO DE VENDA DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3207', 'ANULAÇÃO DE VALOR RELATIVO À VENDA DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3251', 'COMPRA DE ENERGIA ELÉTRICA PARA DISTRIBUIÇÃO OU COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3206', 'ANULAÇÃO DE VALOR RELATIVO À PRESTAÇÃO DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3205', 'ANULAÇÃO DE VALOR RELATIVO À PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3202', 'DEVOLUÇÃO DE VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3211', 'DEVOLUÇÃO DE VENDA DE PRODUÇÃO DO ESTABELECIMENTO SOB O REGIME DE DRAWBACK');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3200', 'DEVOLUÇÕES DE VENDAS DE PRODUÇÃO PRÓPRIA, DE TERCEIROS OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1350', 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1300', 'AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1353', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1352', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1303', 'AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO POR ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1302', 'AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO POR ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1356', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1306', 'AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO POR ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1351', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE PARA EXECUÇÃO DE SERVIÇO DA MESMA NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1301', 'AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO PARA EXECUÇÃO DE SERVIÇO DA MESMA NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1355', 'AQUISI. DE SERVIÇO DE TRANSP. POR ESTABELEC. DE GERADORA OU DE DISTRIB. DE ENERGIA ELETRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1305', 'AQUISI. DE SERVIÇO DE COMUNIC. POR ESTABELEC. DE GERADORA OU DE DISTRIB. DE ENERGIA ELETRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1304', 'AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO POR ESTABELECIMENTO DE PRESTADOR DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1354', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO DE PRESTADOR DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1360', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR CONTRIBUINTE-SUBSTITUTO EM RELAÇÃO AO SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2350', 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2300', 'AQUISIÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2353', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2352', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2303', 'AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO POR ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2302', 'AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO POR ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2356', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2306', 'AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO POR ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2351', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE PARA EXECUÇÃO DE SERVIÇO DA MESMA NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2301', 'AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO PARA EXECUÇÃO DE SERVIÇO DA MESMA NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2355', 'AQUI. DE SERV. DE TRANSP. POR ESTABEL. DE GERADORA OU DE DISTRIBUIDORA DE ENERGIA ELETRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2305', 'AQUIS. DE SERVIÇO DE COMUNIC. POR ESTABELEC. DE GERADORA OU DE DISTRIB. DE ENERGIA ELETRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2304', 'AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO POR ESTABELECIMENTO DE PRESTADOR DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2354', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO DE PRESTADOR DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3350', 'AQUISIÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3352', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3352', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3356', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3301', 'AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO PARA EXECUÇÃO DE SERVIÇO DA MESMA NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3354', 'AQUISIÇÃO DE SERVIÇO DE TRANSPORTE POR ESTABELECIMENTO DE PRESTADOR DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3355', 'AQUI. DE SERVIÇO DE TRANSP. POR ESTABELECIMENTO DE GERADORA OU DE DISTRIB. DE ENERGIA ELETRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1450', 'SISTEMAS DE INTEGRAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1452', 'RETORNO DE INSUMO NÃO UTILIZADO NA PRODUÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1451', 'RETORNO DE ANIMAL DO ESTABELECIMENTO PRODUTOR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1400', 'ENTRADAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1415', 'RET. DE MERC. ADQUI. OU RECEBIDA DE TERCEIROS REMETIDA PARA VENDA FORA DO ESTABELEC.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1408', 'TRANSF. PARA COMERC. EM OPERAÇÃO COM MERC. SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIBUTARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1401', 'COMPRA PARA INDUSTRIALI. OU PROD. RURAL DE MERCADORIA SUJEITA AO REGIME DE SUBST. TRIBUTARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1408', 'TRANSF. PARA INDUST. OU PRODUÇÃO RURAL DE MERC. SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIBUTARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1410', 'DEV. DE VENDA DE MERC. DE PRODUÇÃO DO ESTABELEC., SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIBUTARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1414', 'RETORNO DE MERC. DE PROD. DO ESTABEL. REMETIDA P/ VENDA FORA DO ESTABELEC. SUJEITA A SUBS. TRIB.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1407', 'COMPRA DE MERC. PARA USO OU CONSUMO CUJA MERC. ESTÁ SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIBUTARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1411', 'DEV. DE VENDA DE MERC. ADQUI. OU RECEBIDA DE TERCEIROS EM OPERAÇÃO COM MERC. SUJEITA A SUBS. TRIB.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1403', 'COMPRA PARA COMERCIALIZAÇÃO EM OPERAÇÃO COM MERCADORIA SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1406', 'COMPRA DE BEM PARA O ATIVO IMOBIL. CUJA MERCADORIA ESTÁ SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIBUTARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2415', 'RETORNO DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2411', 'DEV. DE VENDA DE MERC. ADQUIRIDA OU RECEBIDA DE TERCEIROS.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2400', 'ENTRADAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2414', 'RETORNO DE PRODUÇÃO DO ESTABELECIMENTO, REMETIDA PARA VENDA FORA DO ESTABELECIMENTO.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2407', 'COMPRA DE MERC. PARA USO OU CONSUMO CUJA MERC. ESTÁ SUJEITA AO REGIME DE SUBST. TRIB.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2408', 'TRANSF. PARA INDUST. OU PRODUÇÃO RURAL DE MERC. SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIB.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2406', 'COMPRA DE BEM PARA O ATIVO IMOB. CUJA MERCADORIA ESTÁ SUJEITA AO REGIME DE SUBST. TRIBUT.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2410', 'DEV. DE VENDA DE PROD. DO ESTAB. QUANDO O PROD. ESTIVER SUJEITO AO REGIME DE SUBST. TRIBU.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2401', 'COMPRA PARA INDUST. OU PROD. RURAL DE MERCADORIA SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIBUTARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2403', 'COMPRA PARA COMERCIALIZAÇÃO EM OPERAÇÃO COM MERCADORIA SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2409', 'TRANSFERÊNCIA PARA COMERCIALIZAÇÃO EM OPERAÇÃO COM MERCADORIA SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIB');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1551', 'COMPRA DE BEM PARA O ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1556', 'COMPRA DE MATERIAL PARA USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1552', 'TRANSFERÊNCIA DE BEM DO ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1557', 'TRANSFERÊNCIA DE MATERIAL PARA USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1553', 'DEVOLUÇÃO DE VENDA DE BEM DO ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1501', 'ENTRADA DE MERCADORIA RECEBIDA COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1554', 'RETORNO DE BEM DO ATIVO IMOBILIZADO REMETIDO PARA USO FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1555', 'ENTRADA DE BEM DO ATIVO IMOBILIZADO DE TERCEIRO, REMETIDO PARA USO NO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1500', 'ENT. DE MERC. REMETIDAS PARA FORMAÇÃO DE LOTE OU COM FIM ESPECÍFICO DE EXPORT. E EVENTUAIS DEV.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1503', 'ENT. DECORRENTE DE DEV. DE PROD. DE FABRICAÇÃO DO ESTABELEC. REMETIDO COM FIM ESPECCIFICO DE EXP.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1505', 'ENT. DECORRENTE DE DEV. SIMBÓLICA DE MERC. REMETIDA PARA FORMAÇÃO DE LOTE DE EXP. DE PROD. INDUST.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1504', 'ENT. DECORRENTE DE DEV. DE MERC. REMETIDA COM FIM ESPECÍFICO DE EXP., ADQUIRIDA OU RECEBIDAS DE TERC');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1506', 'ENT. DECORRENTE DE DEV. SIMBÓLICA DE MERC. ADQUI. OU RECEB. DE TERCEIROS, REMETIDA PARA FORM DE EXP');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2551', 'COMPRA DE BEM PARA O ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2556', 'COMPRA DE MATERIAL PARA USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2552', 'TRANSFERÊNCIA DE BEM DO ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2557', 'TRANSFERÊNCIA DE MATERIAL PARA USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2553', 'DEVOLUÇÃO DE VENDA DE BEM DO ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2501', 'ENTRADA DE MERCADORIA RECEBIDA COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2554', 'RETORNO DE BEM DO ATIVO IMOBILIZADO REMETIDO PARA USO FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2555', 'ENTRADA DE BEM DO ATIVO IMOBILIZADO DE TERCEIRO, REMETIDO PARA USO NO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2505', 'ENT. DECORRENTE DE DEV. SIMBÓLICA DE MERC. REMETIDA PARA FORMAÇÃO DE LOTE DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2506', 'ENTRADA DECORRENTE DE DEVOLUÇÃO SIMBÓLICA DE MERCADORIA, ADQUIRIDA OU RECEBIDA DE TERCEIROS.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2500', 'ENT. DE MERC. REMETIDAS PARA FORMAÇÃO DE LOTE OU COM FIM ESPECÍFICO DE EXP. E EVENTUAIS DEVOL.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2503', 'ENT. DECORRENTE DE DEV. DE PRODUTO INDUSTRIALIZADO PELO ESTAB. REMETIDO COM FIM ESPEC. DE EXP.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2504', 'ENT. DECORRENTE DE DEV. DE MERC. REMETIDA COM FIM ESPECÍFICO DE EXP. ADQUIRIDA OU RECEB. DE TERC.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3551', 'COMPRA DE BEM PARA O ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3556', 'COMPRA DE MATERIAL PARA USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3500', 'ENTRADAS DE MERCADORIAS REMETIDAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3503', 'DEVOLUÇÃO DE MERCADORIA EXPORTADA QUE TENHA SIDO RECEBIDA COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3551', 'CLASSIFICAM-SE NESTE CÓDIGO AS COMPRAS DE BENS DESTINADOS AO ATIVO IMOBILIZADO DO ESTABELECIMENTO.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1601', 'RECEBIMENTO, POR TRANSFERÊNCIA, DE CRÉDITO DE ICMS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1663', 'ENTRADA DE COMBUSTÍVEL OU LUBRIFICANTE PARA ARMAZENAGEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1603', 'RESSARCIMENTO DE ICMS RETIDO POR SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1652', 'COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1664', 'RETORNO DE COMBUSTÍVEL OU LUBRIFICANTE REMETIDOS PARA ARMAZENAGEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1659', 'TRANSFERÊNCIA DE COMBUSTÍVEL OU LUBRIFICANTE PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1658', 'TRANSFERÊNCIA DE COMBUSTÍVEL OU LUBRIFICANTE PARA INDUSTRIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1653', 'COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE POR CONSUMIDOR OU USUÁRIO FINAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1650', 'ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO, E LUBRIFICANTES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1651', 'COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE PARA INDUSTRIALIZAÇÃO SUBSEQÜENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1604', 'LANÇAMENTO DO CRÉDITO RELATIVO À COMPRA DE BEM PARA O ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1602', 'RECEB POR TRANSF DE SALDO CREDOR DO ICMS DE OUTRO ESTAB DA MESMA EMPRESA.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1605', 'REC. POR TRANSF. DE SALDO DEVEDOR DO ICMS DE OUTRO ESTABELEC.DA MESMA EMPRESA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1661', 'DEVOLUÇÃO DE VENDA DE COMBUSTÍVEL OU LUBRIFICANTE DESTINADOS À COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1662', 'DEVOLUÇÃO DE VENDA DE COMBUSTÍVEL OU LUBRIFICANTE DESTINADOS A CONSUMIDOR OU USUÁRIO FINAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1660', 'DEVOLUÇÃO DE VENDA DE COMBUSTÍVEL OU LUBRIFICANTE DESTINADOS À INDUSTRIALIZAÇÃO SUBSEQÜENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2663', 'ENTRADA DE COMBUSTÍVEL OU LUBRIFICANTE PARA ARMAZENAGEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2603', 'RESSARCIMENTO DE ICMS RETIDO POR SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2652', 'COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2664', 'RETORNO DE COMBUSTÍVEL OU LUBRIFICANTE REMETIDOS PARA ARMAZENAGEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2658', 'TRANSFERÊNCIA DE COMBUSTÍVEL OU LUBRIFICANTE PARA INDUSTRIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2659', 'TRANSFERÊNCIA DE COMBUSTÍVEL OU LUBRIFICANTE PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2653', 'COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE POR CONSUMIDOR OU USUÁRIO FINAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2650', 'ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO, E LUBRIFICANTES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2651', 'COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE PARA INDUSTRIALIZAÇÃO SUBSEQÜENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2661', 'DEVOLUÇÃO DE VENDA DE COMBUSTÍVEL OU LUBRIFICANTE DESTINADOS À COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2662', 'DEVOLUÇÃO DE VENDA DE COMBUSTÍVEL OU LUBRIFICANTE DESTINADOS A CONSUMIDOR OU USUÁRIO FINAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2660', 'DEVOLUÇÃO DE VENDA DE COMBUSTÍVEL OU LUBRIFICANTE DESTINADOS À INDUSTRIALIZAÇÃO SUBSEQÜENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3652', 'COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3653', 'COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE POR CONSUMIDOR OU USUÁRIO FINAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3651', 'COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE PARA INDUSTRIALIZAÇÃO SUBSEQÜENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3650', 'ENTRADAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO, E LUBRIFICANTES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1911', 'ENTRADA DE AMOSTRA GRÁTIS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1920', 'ENTRADA DE VASILHAME OU SACARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1921', 'RETORNO DE VASILHAME OU SACARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1932', 'AQUISIÇÃO DE SERVIÇO DE TRANSP.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1910', 'ENTRADA DE BONIFICAÇÃO, DOAÇÃO OU BRINDE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1901', 'ENTRADA PARA INDUSTRIALIZAÇÃO POR ENCOMENDA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1908', 'ENTRADA DE BEM POR CONTA DE CONTRATO DE COMODATO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1904', 'RETORNO DE REMESSA PARA VENDA FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1912', 'ENTRADA DE MERCADORIA OU BEM RECEBIDO PARA DEMONSTRAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1913', 'RETORNO DE MERCADORIA OU BEM REMETIDO PARA DEMONSTRAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1900', 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1931', 'LANÇAMENTO EFETUADO PELO TOMADOR DO SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1909', 'RETORNO DE BEM REMETIDO POR CONTA DE CONTRATO DE COMODATO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1914', 'RETORNO DE MERCADORIA OU BEM REMETIDO PARA EXPOSIÇÃO OU FEIRA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1915', 'ENTRADA DE MERCADORIA OU BEM RECEBIDO PARA CONSERTO OU REPARO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1916', 'RETORNO DE MERCADORIA OU BEM REMETIDO PARA CONSERTO OU REPARO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1902', 'RETORNO DE MERCADORIA REMETIDA PARA INDUSTRIALIZAÇÃO POR ENCOMENDA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1949', 'OUTRA ENTRADA DE MERCADORIA OU PRESTAÇÃO DE SERVIÇO NÃO ESPECIFICADA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1949', 'OUTRA ENTRADA DE MERCADORIA OU PRESTAÇÃO DE SERVIÇO NÃO ESPECIFICADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1906', 'RETORNO DE MERCADORIA REMETIDA PARA DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1917', 'ENTRADA DE MERCADORIA RECEBIDA EM CONSIGNAÇÃO MERCANTIL OU INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1923', 'ENTRADA DE MERCADORIA RECEBIDA DO VENDEDOR REMETENTE, EM VENDA À ORDEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1918', 'DEVOLUÇÃO DE MERCADORIA REMETIDA EM CONSIGNAÇÃO MERCANTIL OU INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1933', 'AQUISIÇÃO DE SERVIÇO TRIBUTADO PELO IMPOSTO SOBRE SERVIÇOS DE QUALQUER NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1934', 'ENTRADA SIMBÓLICA DE MERCADORIA RECEBIDA PARA DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1907', 'RETORNO SIMBÓLICO DE MERCADORIA REMETIDA PARA DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1905', 'ENTRADA DE MERCADORIA RECEBIDA PARA DEPÓSITO EM DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1903', 'ENTRADA DE MERCADORIA REMETIDA PARA INDUSTRIALIZAÇÃO E NÃO APLICADA NO REFERIDO PROCESSO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1925', 'RETORNO DE MERC. REMETIDA PARA INDUSTRIALIZAÇÃO POR CONTA E ORDEM DO ADQUIRENTE DA MERCADORIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1922', 'LANÇAMENTO EFETUADO A TÍTULO DE SIMPLES FATURAMENTO DECORRENTE DE COMPRA PARA RECEBIMENTO FUTURO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1924', 'ENT. PARA INDUST. POR CONTA E ORDEM DO ADQUIRENTE DA MERC. QUANDO ESTA NÃO TRANSITAR PELO ESTAB.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1919', 'DEV. SIMBÓLICA DE MERC. VENDIDA OU UTILI. EM PROCESSO INDUST. REMETIDA ANTERI. EM CONSIGNAÇAO MERC.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '1926', 'LANÇ. EFETUADO A TÍTULO DE RECLASSIFICAÇÃO DE MERC. DECOR. DE FORMAÇÃO DE KIT OU DE SUA DESAGREGAÇAO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2911', 'ENTRADA DE AMOSTRA GRÁTIS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2920', 'RETORNO DE VASILHAME OU SACARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2920', 'ENTRADA DE VASILHAME OU SACARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2910', 'ENTRADA DE BONIFICAÇÃO, DOAÇÃO OU BRINDE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2901', ' ENTRADA PARA INDUSTRIALIZAÇÃO POR ENCOMENDA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2908', 'ENTRADA DE BEM POR CONTA DE CONTRATO DE COMODATO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2904', 'RETORNO DE REMESSA PARA VENDA FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2912', 'ENTRADA DE MERCADORIA OU BEM RECEBIDO PARA DEMONSTRAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2913', 'RETORNO DE MERCADORIA OU BEM REMETIDO PARA DEMONSTRAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2900', 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2931', 'LANÇAMENTO EFETUADO PELO TOMADOR DO SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2909', 'RETORNO DE BEM REMETIDO POR CONTA DE CONTRATO DE COMODATO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2914', 'RETORNO DE MERCADORIA OU BEM REMETIDO PARA EXPOSIÇÃO OU FEIRA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2915', 'ENTRADA DE MERCADORIA OU BEM RECEBIDO PARA CONSERTO OU REPARO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2916', 'RETORNO DE MERCADORIA OU BEM REMETIDO PARA CONSERTO OU REPARO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2902', 'RETORNO DE MERCADORIA REMETIDA PARA INDUSTRIALIZAÇÃO POR ENCOMENDA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2949', 'OUTRA ENTRADA DE MERCADORIA OU PRESTAÇÃO DE SERVIÇO NÃO ESPECIFICADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2949', 'OUTRA ENTRADA DE MERCADORIA OU PRESTAÇÃO DE SERVIÇO NÃO ESPECIFICADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2949', 'OUTRA ENTRADA DE MERCADORIA OU PRESTAÇÃO DE SERVIÇO NÃO ESPECIFICADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2906', 'RETORNO DE MERCADORIA REMETIDA PARA DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2917', 'ENTRADA DE MERCADORIA RECEBIDA EM CONSIGNAÇÃO MERCANTIL OU INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2923', 'ENTRADA DE MERCADORIA RECEBIDA DO VENDEDOR REMETENTE, EM VENDA À ORDEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2932', 'AQUISIÇÃO DE SERV. DE TRANSP. INICIADO EM UNIDADE DA FEDERAÇÃO DIVERSA.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2918', 'DEVOLUÇÃO DE MERCADORIA REMETIDA EM CONSIGNAÇÃO MERCANTIL OU INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2924', 'ENTRADA PARA INDUSTRIALIZAÇÃO POR CONTA E ORDEM DO ADQUIRENTE DA MERCADORIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2919', 'DEVOLUÇÃO SIMBÓLICA DE MERCADORIA VENDIDA OU UTILIZADA EM PROCESSO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2933', 'AQUISIÇÃO DE SERVIÇO TRIBUTADO PELO IMPOSTO SOBRE SERVIÇOS DE QUALQUER NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2934', 'ENTRADA SIMBÓLICA DE MERCADORIA RECEBIDA PARA DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2907', 'RETORNO SIMBÓLICO DE MERCADORIA REMETIDA PARA DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2905', 'ENTRADA DE MERCADORIA RECEBIDA PARA DEPÓSITO EM DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2903', 'ENTRADA DE MERCADORIA REMETIDA PARA INDUSTRIALIZAÇÃO E NÃO APLICADA NO REFERIDO PROCESSO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2922', 'LANÇAMENTO EFETUADO A TÍTULO DE SIMPLES FATURAMENTO DECORRENTE DE COMPRA PARA RECEBIMENTO FUTURO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '2925', 'RETORNO DE MERCADORIA REMETIDA PARA INDUSTRIALIZAÇÃO POR CONTA E ORDEM DO ADQUIRENTE DA MERCADORIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3900', 'OUTRAS ENTRADAS DE MERCADORIAS OU AQUISIÇÕES DE SERVIÇOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3949', 'OUTRA ENTRADA DE MERCADORIA OU PRESTAÇÃO DE SERVIÇO NÃO ESPECIFICADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('E', '3930', 'LANÇAMENTO EFETUADO A TÍTULO DE ENT. DE BEM SOB AMPARO DE REGIME ESPECIAL ADUANEIRO DE ADMISSÃO TEMP');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5000', 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA O ESTADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6000', 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA OUTROS ESTADOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7000', 'SAÍDAS OU PRESTAÇÕES DE SERVIÇOS PARA O EXTERIOR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5102', 'VENDA DE MERCADORIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5150', 'SISTEMAS DE INTEGRAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5153', 'TRANSFERÊNCIA DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5101', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5100', 'VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5151', 'TRANSFERÊNCIA DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5124', 'INDUSTRIALIZAÇÃO EFETUADA PARA OUTRA EMPRESA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5150', 'TRANSFERÊNCIAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5110', 'VENDA DE MERCADORIA, ADQUIRIDA OU RECEBIDA DE TERCEIROS.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5152', 'TRANSFERÊNCIA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5100', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO QUE NÃO DEVA POR ELE TRANSITAR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5103', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO EFETUADA FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5155', 'TRANSFERÊNCIA DE PRODUÇÃO DO ESTABELECIMENTO, QUE NÃO DEVA POR ELE TRANSITAR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5120', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS ENTREGUE AO DESTINATÁRIO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5116', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO ORIGINADA DE ENCOMENDA PARA ENTREGA FUTURA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5119', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS ENTREGUE AO DESTINATÁRIO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5113', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO REMETIDA ANTERIORMENTE EM CONSIGNAÇÃO MERCANTIL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5111', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO REMETIDA ANTERIORMENTE EM CONSIGNAÇÃO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5106', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, QUE NÃO DEVA POR ELE TRANSITAR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5104', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, EFETUADA FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5125', 'INDUSTRIALIZAÇÃO EFETUADA PARA OUTRA EMPRESA QUANDO A MERCADORIA RECEBIDA PARA UTILIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5155', 'TRANSFERÊNCIA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, QUE NÃO DEVA POR ELE TRANSITAR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5109', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO DESTINADA À ZONA FRANCA DE MANAUS OU ÁREAS DE LIVRE COMÉRCIO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5117', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, ORIGINADA DE ENCOMENDA PARA ENTREGA FUTURA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5112', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS REMETIDA ANTERIORMENTE EM CONSIGNAÇÃO INDUSTR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5122', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO REMETIDA PARA INDUSTRIALIZAÇÃO, POR CONTA E ORDEM DO ADQUIRENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5123', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS REMETIDA PARA INDUSTRIALIZAÇÃO, POR CONTA E O');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5114', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS REMETIDA ANTERIORMENTE EM CONSIGNAÇÃO MERCANT');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5115', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, RECEBIDA ANTERIORMENTE EM CONSIGNAÇÃO MERCAN');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5118', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO ENTREGUE AO DESTIN. POR CONTA E ORDEM DO ADQUIRENTE ORIGINARIO.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6153', 'TRANSFERÊNCIA DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6101', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6151', 'TRANSFERÊNCIA DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6124', 'INDUSTRIALIZAÇÃO EFETUADA PARA OUTRA EMPRESA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6125', 'INDUSTRIALIZAÇÃO EFETUADA PARA OUTRA EMPRESA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6150', 'TRANSFERÊNCIAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6102', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6110', 'VENDA DE MERCADORIA, ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6120', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6152', 'TRANSFERÊNCIA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6107', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO, DESTINADA A NÃO CONTRIBUINTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6122', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO REMETIDA PARA INDUSTRIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6105', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO QUE NÃO DEVA POR ELE TRANSITAR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6103', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO, EFETUADA FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6155', 'TRANSFERÊNCIA DE PRODUÇÃO DO ESTABELECIMENTO, QUE NÃO DEVA POR ELE TRANSITAR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6116', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO ORIGINADA DE ENCOMENDA PARA ENTREGA FUTURA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6119', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS ENTREGUE AO DESTINATARIO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6112', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO REMETIDA ANTERIORMENTE EM CONSIGNAÇÃO MERCANTIL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6108', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, DESTINADA A NÃO CONTRIBUINTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6111', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO REMETIDA ANTERIORMENTE EM CONSIGNAÇÃO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6123', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS REMETIDA PARA INDUSTRIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6106', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, QUE NÃO DEVA POR ELE TRANSITAR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6156', 'TRANSFERÊNCIA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, QUE NÃO DEVA POR ELE TRANSITAR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6109', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO DESTINADA À ZONA FRANCA DE MANAUS OU ÁREAS DE LIVRE COMÉRCIO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6117', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, ORIGINADA DE ENCOMENDA PARA ENTREGA FUTURA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6112', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS REMETIDA ANTERIORMENTE EM CONSIGNAÇÃO INDUST.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6114', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS REMETIDA ANTERIORMENTE EM CONSIGNAÇÃO MERCANT');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6115', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, RECEBIDA ANTERIORMENTE EM CONSIGNAÇÃO MERCAN');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6118', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO ENTREGUE AO DESTINATÁRIO POR CONTA E ORDEM DO ADQUIRENTE ORIGIN');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7101', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7100', 'VENDAS DE PRODUÇÃO PRÓPRIA OU DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7102', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7127', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO SOB O REGIME DE DRAWBACK');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7105', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO, QUE NÃO DEVA POR ELE TRANSITAR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7106', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, QUE NÃO DEVA POR ELE TRANSITAR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5250', 'VENDAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5202', 'DEVOLUÇÃO DE COMPRA PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5258', 'VENDA DE ENERGIA ELÉTRICA A NÃO CONTRIBUINTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5207', 'ANULAÇÃO DE VALOR RELATIVO À COMPRA DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5253', 'VENDA DE ENERGIA ELÉTRICA PARA ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5210', 'DEVOLUÇÃO DE COMPRA PARA UTILIZAÇÃO NA PRESTAÇÃO DE SERVIÇO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5201', 'DEVOLUÇÃO DE COMPRA PARA INDUSTRIALIZAÇÃO OU PRODUÇÃO RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5257', 'VENDA DE ENERGIA ELÉTRICA PARA CONSUMO POR DEMANDA CONTRATADA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5252', 'VENDA DE ENERGIA ELÉTRICA PARA DISTRIBUIÇÃO OU COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5206', 'ANULAÇÃO DE VALOR RELATIVO A AQUISIÇÃO DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5205', 'ANULAÇÃO DE VALOR RELATIVO A AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5256', 'VENDA DE ENERGIA ELÉTRICA PARA ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5209', 'DEVOLUÇÃO DE MERCADORIA RECEBIDA EM TRANSFERÊNCIA PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5254', 'VENDA DE ENERGIA ELÉTRICA PARA ESTABELECIMENTO PRESTADOR DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5255', 'VENDA DE ENERGIA ELÉTRICA PARA ESTABELECIMENTO PRESTADOR DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5208', 'DEVOLUÇÃO DE MERCADORIA RECEBIDA EM TRANSFERÊNCIA PARA INDUSTRIALIZAÇÃO OU PRODUÇÃO RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5200', 'DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, PRODUÇÃO RURAL, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6250', 'VENDAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6202', 'DEVOLUÇÃO DE COMPRA PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6258', 'VENDA DE ENERGIA ELÉTRICA A NÃO CONTRIBUINTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6207', 'ANULAÇÃO DE VALOR RELATIVO À COMPRA DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6253', 'VENDA DE ENERGIA ELÉTRICA PARA ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6252', 'VENDA DE ENERGIA ELÉTRICA PARA ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6210', 'DEVOLUÇÃO DE COMPRA PARA UTILIZAÇÃO NA PRESTAÇÃO DE SERVIÇO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6201', 'DEVOLUÇÃO DE COMPRA PARA INDUSTRIALIZAÇÃO OU PRODUÇÃO RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6257', 'VENDA DE ENERGIA ELÉTRICA PARA CONSUMO POR DEMANDA CONTRATADA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6251', 'VENDA DE ENERGIA ELÉTRICA PARA DISTRIBUIÇÃO OU COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6206', 'ANULAÇÃO DE VALOR RELATIVO A AQUISIÇÃO DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6205', 'ANULAÇÃO DE VALOR RELATIVO A AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6256', 'VENDA DE ENERGIA ELÉTRICA PARA ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6209', 'DEVOLUÇÃO DE MERCADORIA RECEBIDA EM TRANSFERÊNCIA PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6254', 'VENDA DE ENERGIA ELÉTRICA PARA ESTABELECIMENTO PRESTADOR DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6255', 'VENDA DE ENERGIA ELÉTRICA PARA ESTABELECIMENTO PRESTADOR DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6200', 'DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6208', 'DEVOLUÇÃO DE MERCADORIA RECEBIDA EM TRANSFERÊNCIA PARA INDUSTRIALIZAÇÃO OU PRODUÇÃO RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7250', 'VENDAS DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7205', 'DEVOLUÇÃO DE COMPRA PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7251', 'VENDA DE ENERGIA ELÉTRICA PARA O EXTERIOR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7207', 'ANULAÇÃO DE VALOR RELATIVO À COMPRA DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7210', 'DEVOLUÇÃO DE COMPRA PARA UTILIZAÇÃO NA PRESTAÇÃO DE SERVIÇO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7201', 'DEVOLUÇÃO DE COMPRA PARA INDUSTRIALIZAÇÃO OU PRODUÇÃO RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7206', 'ANULAÇÃO DE VALOR RELATIVO A AQUISIÇÃO DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7205', 'ANULAÇÃO DE VALOR RELATIVO À AQUISIÇÃO DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7211', 'DEVOLUÇÃO DE COMPRAS PARA INDUSTRIALIZAÇÃO SOB O REGIME DE DRAWBACK');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7200', ' DEVOLUÇÕES DE COMPRAS PARA INDUSTRIALIZAÇÃO, COMERCIALIZAÇÃO OU ANULAÇÕES DE VALORES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5350', 'PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5300', 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5357', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A NÃO CONTRIBUINTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5307', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO A NÃO CONTRIBUINTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5353', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5352', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5303', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO A ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5302', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO A ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5356', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5306', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO A ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5351', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE PARA EXECUÇÃO DE SERVIÇO DA MESMA NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5301', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO PARA EXECUÇÃO DE SERVIÇO DA MESMA NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5304', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO A ESTABELECIMENTO DE PRESTADOR DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5354', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A ESTABELECIMENTO DE PRESTADOR DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5359', 'PREST. DE SERV. DE TRANSP. A CONTRIBUINTE OU A NÃO-CONTRIBUINTE, QUANDO A MERCADORIA TRANSP.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5360', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A CONTRIBUINTE-SUBSTITUTO EM RELAÇÃO AO SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5355', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A ESTABELECIMENTO DE GERADORA OU DE DISTRIB. DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5305', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO A ESTABELECIMENTO DE GERADORA OU DE DISTRIBUIDORA DE ENERGIA ELÉ');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6350', 'PRESTAÇÕES DE SERVIÇOS DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6300', 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6356', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A NÃO CONTRIBUINTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6307', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO A NÃO CONTRIBUINTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6353', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6352', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6303', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO A ESTABELECIMENTO COMERCIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6302', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO A ESTABELECIMENTO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6356', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6306', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO A ESTABELECIMENTO DE PRODUTOR RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6359', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A CONTRIBUINTE OU A NÃO-CONTRIBUINTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6351', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE PARA EXECUÇÃO DE SERVIÇO DA MESMA NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6301', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO PARA EXECUÇÃO DE SERVIÇO DA MESMA NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6304', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO A ESTABELECIMENTO DE PRESTADOR DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6354', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A ESTABELECIMENTO DE PRESTADOR DE SERVIÇO DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6305', 'PRESTAÇÃO DE SERV. DE COMUNICAÇÃO A ESTAB. DE GERADORA OU DE DISTRIBUIDORA DE ENERGIA ELÉTRICA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6360', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A CONTRIBUINTE SUBSTITUTO EM RELAÇÃO AO SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6355', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE A ESTABELECIMENTO DE GERADORA OU DE DISTRIBUIDORA DE ENERGIA ELÉT');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7358', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7300', 'PRESTAÇÕES DE SERVIÇOS DE COMUNICAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7301', 'PRESTAÇÃO DE SERVIÇO DE COMUNICAÇÃO PARA EXECUÇÃO DE SERVIÇO DA MESMA NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5413', 'DEVOLUÇÃO DE MERCADORIA DESTINADA AO USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5403', 'VENDA DE MERCADORIA, ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5451', 'REMESSA DE ANIMAL E DE INSUMO PARA ESTABELECIMENTO PRODUTOR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5405', 'VENDA DE MERCADORIA SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIB.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5400', 'SAÍDAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5414', 'REMESSA DE PRODUÇÃO DO ESTABELECIMENTO PARA VENDA FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5409', 'TRANSFERÊNCIA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS EM OPERAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5415', 'REMESSA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS PARA VENDA FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5402', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO DE PRODUTO SUJEITO AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5455', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE, ADQUIRIDOS OU RECEBIDOS DE TERCEIROS, DESTINADOS À COMERC.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5408', 'TRANSFERÊNCIA DE PRODUÇÃO DO ESTABELECIMENTO QUANDO O PRODUTO ESTIVER SUJEITO AO REGIME DE SUBST.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5412', 'DEVOLUÇÃO DE BEM DO ATIVO IMOBILIZADO, EM OPERAÇÃO COM MERCADORIA SUJEITA AO REGIME DE SUBST. TRIB.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5410', 'DEVOLUÇÃO DE COMPRA PARA INDUSTRIALIZAÇÃO DE MERCADORIA SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5401', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO QUANDO O PRODUTO ESTEJA SUJEITO AO REGIME DE SUBSTITUIÇÃO TRIB.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5411', 'DEVOLUÇÃO DE COMPRA PARA COMERCIALIZAÇÃO EM OPERAÇÃO COM MERCADORIA SUJEITA AO REGIME DE SUBST. TRIB');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6413', 'DEVOLUÇÃO DE MERCADORIA DESTINADA AO USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6403', 'VENDA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6410', 'DEVOLUÇÃO DE COMPRA PARA INDUSTRIALIZAÇÃO OU PTRODUÇÃO RURAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6404', 'VENDA DE MERCADORIA SUJEITA AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6400', 'SAÍDAS DE MERCADORIAS SUJEITAS AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6414', 'REMESSA DE PRODUÇÃO DO ESTABELECIMENTO PARA VENDA FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6415', 'REMESSA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS PARA VENDA FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6402', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO DE PRODUTO SUJEITO AO REGIME DE SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6401', 'VENDA DE PRODUÇÃO DO ESTABELECIMENTO QUANDO O PRODUTO ESTIVER SUJEITO AO REGIME DE SUBST. TRIB.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6412', 'DEVOLUÇÃO DE BEM DO ATIVO IMOBILIZADO, EM OPERAÇÃO COM MERCADORIA SUJEITA AO REGIME DE SUBST. TRIB.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6409', 'TRANSFERÊNCIA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, SUJEITA AO REGIME DE SUBSTIT. TRIB.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6411', 'DEVOLUÇÃO DE COMPRA PARA COMERCIALIZAÇÃO EM OPERAÇÃO COM MERCADORIA SUJEITA AO REGIME DE SUBST. TRIB');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6408', 'TRANSFERÊNCIA DE PRODUÇÃO DO ESTABELECIMENTO QUANDO O PROD. ESTIVER SUJEITO AO REGIME DE SUBST. TRIB');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5551', 'VENDA DE BEM DO ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5552', 'TRANSFERÊNCIA DE BEM DO ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5557', 'TRANSFERÊNCIA DE MATERIAL DE USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5556', 'DEVOLUÇÃO DE COMPRA DE MATERIAL DE USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5553', 'DEVOLUÇÃO DE COMPRA DE BEM PARA O ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5503', 'DEVOLUÇÃO DE MERCADORIA RECEBIDA COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5554', 'REMESSA DE BEM DO ATIVO IMOBILIZADO PARA USO FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5501', 'REMESSA DE PRODUÇÃO DO ESTABELECIMENTO, COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5504', 'REMESSA DE MERCADORIA PARA FORMAÇÃO DE LOTE DE EXPORTAÇÃO, DE PRODUTO INDUSTRIALIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5555', 'DEVOLUÇÃO DE BEM DO ATIVO IMOBILIZADO DE TERCEIRO, RECEBIDO PARA USO NO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5500', 'REMESSAS PARA FORMAÇÃO DE LOTE E COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5502', 'REMESSA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5505', 'REMESSA DE MERCADORIA, ADQUIRIDA OU RECEBIDA DE TERCEIROS, PARA FORMAÇÃO DE LOTE DE EXPORTAÇÃO.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6551', 'VENDA DE BEM DO ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6552', 'TRANSFERÊNCIA DE BEM DO ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6557', 'TRANSFERÊNCIA DE MATERIAL DE USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6556', 'DEVOLUÇÃO DE COMPRA DE MATERIAL DE USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6553', 'DEVOLUÇÃO DE COMPRA DE BEM PARA O ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6504', 'REMESSA DE MERCADORIA PARA FORMAÇÃO DE LOTE DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6500', 'REMESSAS COM FIM ESPECÍFICO DE EXPORTAÇÃO E EVENTUAIS DEVOLUÇÕES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6503', 'DEVOLUÇÃO DE MERCADORIA RECEBIDA COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6554', 'REMESSA DE BEM DO ATIVO IMOBILIZADO PARA USO FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6501', 'REMESSA DE PRODUÇÃO DO ESTABELECIMENTO, COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6555', 'DEVOLUÇÃO DE BEM DO ATIVO IMOBILIZADO DE TERCEIRO, RECEBIDO PARA USO NO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6502', 'REMESSA DE MERCADORIA ADQUIRIDA OU RECEBIDA DE TERCEIROS, COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6505', 'REMESSA DE MERCADORIA, ADQUIRIDA OU RECEBIDA DE TERCEIROS, PARA FORMAÇÃO DE LOTE DE EXPORTAÇÃO.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7551', 'VENDA DE BEM DO ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7553', 'DEVOLUÇÃO DE COMPRA DE BEM PARA O ATIVO IMOBILIZADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7500', 'EXPORTAÇÃO DE MERCADORIAS RECEBIDAS COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7501', 'EXPORTAÇÃO DE MERCADORIAS RECEBIDAS COM FIM ESPECÍFICO DE EXPORTAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7550', 'OPERAÇÕES COM BENS DE ATIVO IMOBILIZADO E MATERIAIS PARA USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
COMMIT WORK;
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5601', 'TRANSFERÊNCIA DE CRÉDITO DE ICMS ACUMULADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5663', 'REMESSA PARA ARMAZENAGEM DE COMBUSTÍVEL OU LUBRIFICANTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5603', 'RESSARCIMENTO DE ICMS RETIDO POR SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5664', 'RETORNO DE COMBUSTÍVEL OU LUBRIFICANTE RECEBIDOS PARA ARMAZENAGEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5667', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE A CONSUMIDOR OU USUÁRIO FINAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5650', 'SAÍDAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO, E LUBRIFICANTES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5665', 'RETORNO SIMBÓLICO DE COMBUSTÍVEL OU LUBRIFICANTE RECEBIDOS PARA ARMAZENAGEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5658', 'TRANSFERÊNCIA DE COMBUSTÍVEL OU LUBRIFICANTE DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5605', 'TRANSFERÊNCIA DE SALDO DEVEDOR DO ICMS DE OUTRO ESTABELECIMENTO DA MESMA EMPRESA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5659', 'TRANSFERÊNCIA DE COMBUSTÍVEL OU LUBRIFICANTE ADQUIRIDOS OU RECEBIDOS DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5661', 'DEVOLUÇÃO DE COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE ADQUIRIDOS PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5602', 'TRANSFERÊNCIA DE SALDO CREDOR DO ICMS, PARA OUTRO ESTABELECIMENTO DA MESMA EMPRESA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5606', 'UTILIZAÇÃO DE SALDO CREDOR DO ICMS PARA EXTINÇÃO POR COMPENSAÇÃO DE DÉBITOS FISCAIS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5662', 'DEVOLUÇÃO DE COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE ADQUIRIDOS POR CONSUMIDOR OU USUÁRIO FINAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5653', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE, DE PRODUÇÃO DO ESTABELECIMENTO, DESTINADOS A CONSUMIDOR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5660', 'DEVOLUÇÃO DE COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE ADQUIRIDOS PARA INDUSTRIALIZAÇÃO SUBSEQÜENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5654', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE, ADQUIRIDOS OU RECEBIDOS DE TERCEIROS, DESTINADOS À INDUST.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5651', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE DE PRODUÇÃO DO ESTABELECIMENTO DESTINADOS À INDUSTRIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5652', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE, DE PRODUÇÃO DO ESTABELECIMENTO, DESTINADOS À COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5666', 'REMESSA, POR CONTA E ORDEM DE TERCEIROS, DE COMBUSTÍVEL OU LUBRIFICANTE RECEBIDOS PARA ARMAZENAGEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5656', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE, ADQUIRIDOS OU RECEBIDOS DE TERCEIROS, DESTINADOS A CONSUMIDOR');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5657', 'REMESSA DE COMBUSTÍVEL OU LUBRIFICANTE, ADQUIRIDOS OU RECEBIDOS DE TERCEIROS, PARA VENDA FORA DO EST');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6600', 'CRÉDITOS E RESSARCIMENTOS DE ICMS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6663', 'REMESSA PARA ARMAZENAGEM DE COMBUSTÍVEL OU LUBRIFICANTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6603', 'RESSARCIMENTO DE ICMS RETIDO POR SUBSTITUIÇÃO TRIBUTÁRIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6664', 'RETORNO DE COMBUSTÍVEL OU LUBRIFICANTE RECEBIDOS PARA ARMAZENAGEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6667', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE A CONSUMIDOR OU USUÁRIO FINAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6651', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE, DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6652', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE, DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6653', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE, DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6650', 'SAÍDAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO, E LUBRIFICANTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6654', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE, ADQUIRIDOS OU RECEBIDOS DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6655', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE, ADQUIRIDOS OU RECEBIDOS DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6665', 'RETORNO SIMBÓLICO DE COMBUSTÍVEL OU LUBRIFICANTE RECEBIDOS PARA ARMAZENAGEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6656', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE, ADQUIRIDOS OU RECEBIDOS DE TERCEIROS,');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6658', 'TRANSFERÊNCIA DE COMBUSTÍVEL OU LUBRIFICANTE DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6657', 'REMESSA DE COMBUSTÍVEL OU LUBRIFICANTE, ADQUIRIDOS OU RECEBIDOS DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6659', 'TRANSFERÊNCIA DE COMBUSTÍVEL OU LUBRIFICANTE ADQUIRIDOS OU RECEBIDOS DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6661', 'DEVOLUÇÃO DE COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE ADQUIRIDOS PARA COMERCIALIZAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6662', 'DEVOLUÇÃO DE COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE ADQUIRIDOS POR CONSUMIDOR OU USUÁRIO FINAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6660', 'DEVOLUÇÃO DE COMPRA DE COMBUSTÍVEL OU LUBRIFICANTE ADQUIRIDOS PARA INDUSTRIALIZAÇÃO SUBSEQÜENTE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6666', 'REMESSA, POR CONTA E ORDEM DE TERCEIROS, DE COMBUSTÍVEL OU LUBRIFICANTE RECEBIDOS PARA ARMAZENAGEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7650', 'DEVOLUÇÃO DE COMPRA DE MATERIAL DE USO OU CONSUMO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7667', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE A CONSUMIDOR OU USUÁRIO FINAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7651', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE DE PRODUÇÃO DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7650', 'SAÍDAS DE COMBUSTÍVEIS, DERIVADOS OU NÃO DE PETRÓLEO, E LUBRIFICANTES');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7654', 'VENDA DE COMBUSTÍVEL OU LUBRIFICANTE ADQUIRIDOS OU RECEBIDOS DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5719', 'DEVOLUÇÃO SIMBÓLICA DE MERCADORIA VENDIDA OU UTILIZADA EM PROCESSO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5911', 'REMESSA DE AMOSTRA GRÁTIS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5920', 'REMESSA DE VASILHAME OU SACARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5921', 'DEVOLUÇÃO DE VASILHAME OU SACARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5910', 'REMESSA EM BONIFICAÇÃO, DOAÇÃO OU BRINDE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5904', 'REMESSA PARA VENDA FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5901', 'REMESSA PARA INDUSTRIALIZAÇÃO POR ENCOMENDA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5912', 'REMESSA DE MERCADORIA OU BEM PARA DEMONSTRAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5905', 'REMESSA PARA DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5908', 'REMESSA DE BEM POR CONTA DE CONTRATO DE COMODATO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5914', 'REMESSA DE MERCADORIA OU BEM PARA EXPOSIÇÃO OU FEIRA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5915', 'REMESSA DE MERCADORIA OU BEM PARA CONSERTO OU REPARO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5900', 'OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5913', 'RETORNO DE MERCADORIA OU BEM RECEBIDO PARA DEMONSTRAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5909', 'RETORNO DE BEM RECEBIDO POR CONTA DE CONTRATO DE COMODATO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5917', 'REMESSA DE MERCADORIA EM CONSIGNAÇÃO MERCANTIL OU INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5916', 'RETORNO DE MERCADORIA OU BEM RECEBIDO PARA CONSERTO OU REPARO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5902', 'RETORNO DE MERCADORIA UTILIZADA NA INDUSTRIALIZAÇÃO POR ENCOMENDA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5949', 'OUTRA SAÍDA DE MERCADORIA OU PRESTAÇÃO DE SERVIÇO NÃO ESPECIFICADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5906', 'RETORNO DE MERCADORIA DEPOSITADA EM DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5923', 'REMESSA DE MERCADORIA POR CONTA E ORDEM DE TERCEIROS, EM VENDA À ORDEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5918', 'DEVOLUÇÃO DE MERCADORIA RECEBIDA EM CONSIGNAÇÃO MERCANTIL OU INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5924', 'REMESSA PARA INDUSTRIALIZAÇÃO POR CONTA E ORDEM DO ADQUIRENTE DA MERCADORIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5933', 'PRESTAÇÃO DE SERVIÇO TRIBUTADO PELO IMPOSTO SOBRE SERVIÇOS DE QUALQUER NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5907', 'RETORNO SIMBÓLICO DE MERCADORIA DEPOSITADA EM DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5934', 'REMESSA SIMBÓLICA DE MERCADORIA DEPOSITADA EM ARMAZÉM GERAL OU DEPÓSITO FECHADO.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5929', 'LANÇAMENTO EFETUADO EM DECORRÊNCIA DE EMISSÃO DE DOCUMENTO FISCAL RELATIVO A OPERAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5903', 'RETORNO DE MERCADORIA RECEBIDA PARA INDUSTRIALIZAÇÃO E NÃO APLICADA NO REFERIDO PROCESSO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5922', 'LANÇAMENTO EFETUADO A TÍTULO DE SIMPLES FATURAMENTO DECORRENTE DE VENDA PARA ENTREGA FUTURA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5926', 'LANÇAMENTO EFETUADO A TÍTULO DE RECLASSIFICAÇÃO DE MERCADORIA DECORRENTE DE FORMAÇÃO DE KIT');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5927', 'LANÇAMENTO EFETUADO A TÍTULO DE BAIXA DE ESTOQUE DECORRENTE DE PERDA, ROUBO OU DETERIORAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5931', 'LANÇAMENTO EFETUADO EM DECORRÊNCIA DA RESPONSABILIDADE DE RETENÇÃO DO IMPOSTO POR SUBST. TRIBU.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5925', 'RETORNO DE MERCADORIA RECEBIDA PARA INDUSTRIALIZAÇÃO POR CONTA E ORDEM DO ADQUIRENTE DA MERCADORIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5928', 'LANÇAMENTO EFETUADO A TÍTULO DE BAIXA DE ESTOQUE DECORRENTE DO ENCERRAMENTO DA ATIVIDADE DA EMPRESA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '5932', 'PRESTAÇÃO DE SERVI. DE TRANSP. INICIADA EM UNID. DA FEDERAÇÃO DIVERSA DAQUELA ONDE INSCRITO O PREST.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6911', 'REMESSA DE AMOSTRA GRÁTIS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6920', 'REMESSA DE VASILHAME OU SACARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6921', 'DEVOLUÇÃO DE VASILHAME OU SACARIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6910', 'REMESSA EM BONIFICAÇÃO, DOAÇÃO OU BRINDE');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6904', 'REMESSA PARA VENDA FORA DO ESTABELECIMENTO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6901', 'REMESSA PARA INDUSTRIALIZAÇÃO POR ENCOMENDA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6912', 'REMESSA DE MERCADORIA OU BEM PARA DEMONSTRAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6905', 'REMESSA PARA DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6908', 'REMESSA DE BEM POR CONTA DE CONTRATO DE COMODATO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6923', 'REMESSA DE MERCADORIA POR CONTA E ORDEM DE TERCEIROS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6914', 'REMESSA DE MERCADORIA OU BEM PARA EXPOSIÇÃO OU FEIRA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6915', 'REMESSA DE MERCADORIA OU BEM PARA CONSERTO OU REPARO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6900', 'OUTRAS SAÍDAS DE MERCADORIAS OU PRESTAÇÕES DE SERVIÇOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6913', 'RETORNO DE MERCADORIA OU BEM RECEBIDO PARA DEMONSTRAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6909', 'RETORNO DE BEM RECEBIDO POR CONTA DE CONTRATO DE COMODATO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6917', 'REMESSA DE MERCADORIA EM CONSIGNAÇÃO MERCANTIL OU INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6916', 'RETORNO DE MERCADORIA OU BEM RECEBIDO PARA CONSERTO OU REPARO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6902', 'RETORNO DE MERCADORIA UTILIZADA NA INDUSTRIALIZAÇÃO POR ENCOMENDA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6949', 'OUTRA SAÍDA DE MERCADORIA OU PRESTAÇÃO DE SERVIÇO NÃO ESPECIFICADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6906', 'RETORNO DE MERCADORIA DEPOSITADA EM DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6918', 'DEVOLUÇÃO DE MERCADORIA RECEBIDA EM CONSIGNAÇÃO MERCANTIL OU INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6932', 'PRESTAÇÃO DE SERVIÇO DE TRANSPORTE INICIADA EM UNIDADE DA FEDERAÇÃO DIVERSA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6924', 'REMESSA PARA INDUSTRIALIZAÇÃO POR CONTA E ORDEM DO ADQUIRENTE DA MERCADORIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6919', 'DEVOLUÇÃO SIMBÓLICA DE MERCADORIA VENDIDA OU UTILIZADA EM PROCESSO INDUSTRIAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6934', 'REMESSA SIMBÓLICA DE MERCADORIA DEPOSITADA EM ARMAZÉM GERAL OU DEPÓSITO FECHADO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6907', 'RETORNO SIMBÓLICO DE MERCADORIA DEPOSITADA EM DEPÓSITO FECHADO OU ARMAZÉM GERAL');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6933', 'PRESTAÇÃO DE SERVIÇO TRIBUTADO PELO IMPOSTO SOBRE SERVIÇOS DE QUALQUER NATUREZA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6929', 'LANÇAMENTO EFETUADO EM DECORRÊNCIA DE EMISSÃO DE DOCUMENTO FISCAL RELATIVO A OPERAÇÃO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6903', 'RETORNO DE MERCADORIA RECEBIDA PARA INDUSTRIALIZAÇÃO E NÃO APLICADA NO REFERIDO PROCESSO');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6922', 'LANÇAMENTO EFETUADO A TÍTULO DE SIMPLES FATURAMENTO DECORRENTE DE VENDA PARA ENTREGA FUTURA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6931', 'LANÇAMENTO EFETUADO EM DECORRÊNCIA DA RESPONSABILIDADE DE RETENÇÃO DO IMPOSTO POR SUBST. TRIBUT.');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '6925', 'RETORNO DE MERCADORIA RECEBIDA PARA INDUSTRIALIZAÇÃO POR CONTA E ORDEM DO ADQUIRENTE DA MERCADORIA');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7930', 'LANÇAMENTO EFETUADO A TÍTULO DE DEVOLUÇÃO DE BEM');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7900', 'OUTRAS SAIDAS DE MERCADORIA OU PRESTAÇÕES DE SERVIÇOS');
INSERT INTO CFOP (TIPO, CFOP, DESCRICAO)
          VALUES ('S', '7994', 'OUTRA SAÍDA DE MERCADORIA OU PRESTAÇÃO DE SERVIÇO NÃO ESPECIFICADO');

COMMIT WORK;
